### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by ljh14** [bupt-ipcr/RL4Net-TE#1]
It seems that CUDA does not work in this framework when I run the last command in the introduction 'pytest test_installation.py'.
The error information is :
OSError: libcudart-80664282.so.10.2: cannot open shared object file: No such file or directory. How to solve this problem? And I do not need CUDA when training agent. Is there any method for installing without CUDA?
Thanks.

**Comment by LampV** [comment]
Can you provide more detail of the error :) 

CUDA is used by RL4Net-lib, main code of DDPG at 
`RL4Net-lib/wujiawei-home/wjwgym/agents/DDPGBase.py`. It is designed to automatically detect whether CUDA is available, with `torch.cuda.is_available()`.  
you can   
1. Checkout in which statement the error is raise
2. Try to replace `torch.cuda.is_avaiable()` with just `False`
3. or forget `RL4Net-lib` and build your own agent directly base on tensorflow or pytorch  

Thanks for your feedback, we will continue to pay attention to this issue.

**Comment by ljh14** [comment]
Thanks for you quick reply. The detail of the error is:
_==================================== ERRORS ====================================
____________________ ERROR collecting test_installation.py _____________________
test_installation.py:15: in <module>
    from wjwgym.agents import DDPGBase
../../.local/lib/python3.6/site-packages/wjwgym/agents/__init__.py:11: in <module>
    from .DDPG_base import DDPGBase
../../.local/lib/python3.6/site-packages/wjwgym/agents/DDPG_base.py:10: in <module>
    from .Utils import ExpReplay, soft_update, OUProcess
../../.local/lib/python3.6/site-packages/wjwgym/agents/Utils.py:10: in <module>
    import torch
../../.local/lib/python3.6/site-packages/torch/__init__.py:135: in <module>
    _load_global_deps()
../../.local/lib/python3.6/site-packages/torch/__init__.py:93: in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
../../miniconda3/envs/ns3_ljh/lib/python3.6/ctypes/__init__.py:348: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: libcudart-80664282.so.10.2: cannot open shared object file: No such file or directory
=========================== short test summary info ============================
ERROR test_installation.py - OSError: libcudart-80664282.so.10.2: cannot open...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.34s ===============================_

**Comment by LampV** [comment]
It seems like a problem of installation about pytorch in our tutorial, the error is raise when import `torch`.  
The code is tested on Ubuntu 18.04, using conda to install pytorch. Conda will help you manage your cudatoolkit.
More about pytorch installations at https://pytorch.org/, `QUICK START 
LOCALLY`, such as `conda install pytorch torchvision cpuonly -c pytorch`.  
Replay us if it works, thanks.

**Comment by ljh14** [comment]
> It seems like a problem of installation about pytorch in our tutorial, the error is raise when import `torch`.
> The code is tested on Ubuntu 18.04, using conda to install pytorch. Conda will help you manage your cudatoolkit.
> More about pytorch installations at https://pytorch.org/, `QUICK START LOCALLY`, such as `conda install pytorch torchvision cpuonly -c pytorch`.
> Replay us if it works, thanks.

I reinstalled the whole environment. And when it executes the last command **pytest**, it shows like:

> =============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.7.7, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/ljh/RL4Net-master
collected 6 items                                                                                                                                                                                                 

test_installation.py 
,and the program don't stop, is it already successfully installed ?

**Comment by LampV** [comment]
If there's no error, RL4Net is now successfully installed, you can try a example like  
```bash
python  TE-trainer/AC-trainer.py
```
Thanks for your replay, we'll update readme as soon as possible
